//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class AutodeskUser
    {
        
        public string username { get; set; }
        public string firstName { get; set; }
        public string lastname { get; set; }
        public string userPassword { get; set; }
    }
}
